home-work-2
js-tasks-ru/js-20220418_konstantinneberekutin pull request #2
Opened 2022-04-22 09:49 UTC by KonstantinNeb

2022-04-22 09:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-22 10:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-22 11:45 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-22 19:19 UTC, dragozin requested changes

2022-04-22 19:19 UTC, dragozin commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return str1.localeCompare(str2, ['ru'], { caseFirst: "upper" });
Желательно добавить еще поддержку английских символов, согласно условию задачи.

2022-04-22 19:19 UTC, dragozin commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return [...arr].sort((str1, str2) =>
👍лайк за использование spread синтаксиса

2022-04-22 19:19 UTC, dragozin commented on 02-javascript-data-types/1-sort-strings/index.js
> +    param === "asc" ? compareString(str1, str2) : compareString(str2, str1)
Отсутствие обработки не корректного параметра направления сортировки может привести к ошибке на реальном проекте.
Представьте, что разработчик ошибся и вместо 'desc' передал 'decs' и будет ожидать что массив отсортируется по убыванию. И такая небольшая ошибка может стоить разработчику времени для отладки.
Как совет: лучше выбросить явную ошибку, если пришло не корректное значение параметра.

2022-04-22 19:19 UTC, dragozin commented on 02-javascript-data-types/2-pick/index.js
> +    newObj[field] = obj[field];
данное решение необходимо доработать.
в объекте `obj` поле `field` может отсутствовать. Хотя в результирующий объект оно попадет со значением undefined.

2022-04-25 09:21 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-25 09:48 UTC, dragozin approved these changes

2022-04-25 09:48 UTC, dragozin commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return 'error';
Для генерации ошибки лучше подойдет явная генерация через инструкцию [throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw)
```
   throw new Error('error');
```

2022-04-25 09:48 UTC, merged