home-work-3
js-tasks-ru/js-20220418_konstantinneberekutin pull request #3
Opened 2022-04-27 21:14 UTC by KonstantinNeb

2022-04-27 21:16 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-28 10:54 UTC, dragozin requested changes

2022-04-28 10:54 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  return (obj) => {
Решение будет не корректно работать на таких примерах:
```
const path = 'hello.world';
const object = {hello: 'HI'};
const getter = createGetter(path);
getter(object)
```
этот пример вернет 'Hi', хотя пути `hello.world` в объекте нет.

пример 2:
```
const object2 = {hello: null}
getter(object2)
```
выдаст ошибку.

Предлагаю поправить эти ошибки.

2022-05-03 18:17 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-05-04 16:19 UTC, dragozin approved these changes

2022-05-04 16:19 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (typeof newObj[field] === "object") {
не забывайте важную особенность, что

```
typeof null === 'object'
```

2022-05-04 16:20 UTC, merged